### ISSUE TITLE
skinsdb: incompatibility

### ISSUE THREAD

**Issue by mazes-80** [sirrobzeroone/3d_armor_flyswim#4] opened 2021-02-07 23:01 UTC
Swim and fly animations not applied when using: [skinsdb](https://github.com/minetest-mods/skinsdb).
Still when 'swimming' the head looks the sky (swim is detected).

I still like to be able to change skin so simple-skins seems to be an altenative.

**Comment by sirrobzeroone** [comment] 2022-08-03 08:32
Just spent a few hours playing around with skinsdb and making fly/swim work with it is going to be a bit of work. Basically it uses it's own custom model for the player character. I'll need to rip my animations out of my .blend model and then apply them to the blend file for skinsdb....That is alot easier said than done I'm not that good/confident with blender yet. Not sure if I can copy individual animations over.

**Comment by sirrobzeroone** [comment] 2022-08-03 12:21
Got skinsdb working if you see this current master supports skinsdb with and without 3d_armor. i havent finished testing but once I do I'll do a fresh release and close this issue.

**Comment by sirrobzeroone** [comment] 2022-08-15 11:49
Should be fixed in 5.6.0.1 release - https://github.com/sirrobzeroone/3d_armor_flyswim/releases/tag/5.6.0.1

**Closed as completed by sirrobzeroone** 2022-08-15 11:49 UTC

**Comment by PavanLuca** [comment] 2023-08-18 12:54
The issue may have been fixed but applying X Bows it happens again.

**Comment by mazes-80** [comment] 2023-08-19 00:53
> The issue may have been fixed but applying X Bows it happens again.

Can you be a bit more verbose. I use x_bows and have no issues, but I moved from skinsdb to simple_skins.

**Comment by PavanLuca** [comment] 2023-08-19 20:01
I don't know much more either, all I know is that this issue happens only with x_bows and 3d_armor_flyswim, of course beyond the default Minetest Game mod. I know because I disabled any other mods till leaving these 3. Maybe the problem is a dependencies conflict of one of these mods.
